### ISSUE TITLE
i try to install this library but there is a lot of errors ? why ?  

### ISSUE THREAD

**Issue by spatchola** [ekarak/BoostStomp#5]
---

some of errors 

---

 ^
/usr/include/boost/type_traits/detail/bool_trait_def.hpp:4:1: error: stray ‘\21’ in                                                                                      program
/usr/include/boost/type_traits/detail/bool_trait_def.hpp:4:1: error: stray ‘\231’ i                                                                                     n program
/usr/include/boost/type_traits/detail/bool_trait_def.hpp:4:1: error: stray ‘\36’ in                                                                                      program
/usr/include/boost/type_traits/detail/bool_trait_def.hpp:4:1: error: stray ‘\251’ i                                                                                     n program
/usr/include/boost/type_traits/detail/bool_trait_def.hpp:4:1: error: stray ‘\270’ i                                                                                     n program
/usr/include/boost/type_traits/detail/bool_trait_def.hpp:5:1: error: stray ‘\302’ i                                                                                     n program
/usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\26’ in program
/usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\212’ in program
/usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\242’ in program
/usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\300’ in program
/usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\177’ in program
/usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\374’ in program
/usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\367’ in program
/usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\23’ in program
/usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\315’ in program
/usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\227’ in program
/usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\214’ in program
/usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\20’ in program
/usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\327’ in program
/usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\235’ in program
/usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\16’ in program
/usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\261’ in program
/usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\330’ in program
/usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\33’ in program
/usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\245’ in program
/usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\265’

**Comment by ekarak** [comment]
Please check your boost library installation. What are the contents of
these header files?

2016-06-01 17:52 GMT+03:00 spatchola notifications@github.com:

> ---
> 
> ## some of errors
> 
> ^
> /usr/include/boost/type_traits/detail/bool_trait_def.hpp:4:1: error: stray
> ‘\21’ in program
> /usr/include/boost/type_traits/detail/bool_trait_def.hpp:4:1: error: stray
> ‘\231’ i n program
> /usr/include/boost/type_traits/detail/bool_trait_def.hpp:4:1: error: stray
> ‘\36’ in program
> /usr/include/boost/type_traits/detail/bool_trait_def.hpp:4:1: error: stray
> ‘\251’ i n program
> /usr/include/boost/type_traits/detail/bool_trait_def.hpp:4:1: error: stray
> ‘\270’ i n program
> /usr/include/boost/type_traits/detail/bool_trait_def.hpp:5:1: error: stray
> ‘\302’ i n program
> /usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\26’ in
> program
> /usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\212’ in
> program
> /usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\242’ in
> program
> /usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\300’ in
> program
> /usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\177’ in
> program
> /usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\374’ in
> program
> /usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\367’ in
> program
> /usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\23’ in
> program
> /usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\315’ in
> program
> /usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\227’ in
> program
> /usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\214’ in
> program
> /usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\20’ in
> program
> /usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\327’ in
> program
> /usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\235’ in
> program
> /usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\16’ in
> program
> /usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\261’ in
> program
> /usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\330’ in
> program
> /usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\33’ in
> program
> /usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\245’ in
> program
> /usr/include/boost/type_traits/config.hpp:21:1: error: stray ‘\265’
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/ekarak/BoostStomp/issues/5, or mute the thread
> https://github.com/notifications/unsubscribe/AAj4KSPgrjoS5k4dBfIRx7WPn8QPSI2_ks5qHZy_gaJpZM4IromX
> .

## 

Elias Karakoulakis
Electrical & Computer Engineer NTUA Athens
Msc Information Systems, AUEB Athens
KNX Advanced Partner

**Comment by spatchola** [comment]
just symbols ... !! but the others header are legible

![screenshot 104](https://cloud.githubusercontent.com/assets/11449247/15717014/52bd9106-2825-11e6-94e2-4e6d00fba520.png)

**Comment by spatchola** [comment]
## finally :D i found the solution for this problem , i downloaded all the boost project and just replace the old headers with the new ones :D but now i have other error 

g++ -c  -fPIC -I . -o BoostStomp.o BoostStomp.cpp
BoostStomp.cpp: In member function ‘void STOMP::BoostStomp::start_stomp_read_headers()’:
BoostStomp.cpp:228:67: error: reference to ‘placeholders’ is ambiguous
         boost::bind(&BoostStomp::handle_stomp_read_headers, this, placeholders::error()));
In file included from /usr/include/boost/asio.hpp:82:0,
                 from BoostStomp.cpp:30:
/usr/include/boost/asio/placeholders.hpp:28:24: note: candidates are: namespace boost::asio::placeholders { }
 namespace placeholders {

##                         ^

why this problem with the placeholders !!!

**Comment by ekarak** [comment]
can you please prepend the namespace "boost::asio::" to the affected line
(BoostStomp.cpp:228) ?

2016-06-06 16:29 GMT+03:00 spatchola notifications@github.com:

> finally :D i found the solution for this problem , i downloaded all the
> boost project and just replace the old headers with the new ones :D but now
> i have other error
> 
> g++ -c -fPIC -I . -o BoostStomp.o BoostStomp.cpp
> BoostStomp.cpp: In member function ‘void
> STOMP::BoostStomp::start_stomp_read_headers()’:
> BoostStomp.cpp:228:67: error: reference to ‘placeholders’ is ambiguous
> boost::bind(&BoostStomp::handle_stomp_read_headers, this,
> placeholders::error()));
> In file included from /usr/include/boost/asio.hpp:82:0,
> from BoostStomp.cpp:30:
> /usr/include/boost/asio/placeholders.hpp:28:24: note: candidates are:
> namespace boost::asio::placeholders { }
> namespace placeholders {
> ^
> 
> why this problem with the placeholders !!!
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/ekarak/BoostStomp/issues/5#issuecomment-223958692,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAj4Kf-OjhcsNlsxGQef8SSiCg8XHcM7ks5qJCCmgaJpZM4IromX
> .

## 

Elias Karakoulakis
Electrical & Computer Engineer NTUA Athens
Msc Information Systems, AUEB Athens
KNX Advanced Partner

**Comment by spatchola** [comment]
## i still have a problem !!! 

BoostStomp.cpp: In member function ‘void STOMP::BoostStomp::start_stomp_read_headers()’:
BoostStomp.cpp:228:20: error: expected primary-expression before ‘(’ token
         boost::asio(&BoostStomp::handle_stomp_read_headers, this, placeholders::error()));
                    ^
BoostStomp.cpp:228:67: error: reference to ‘placeholders’ is ambiguous
         boost::asio(&BoostStomp::handle_stomp_read_headers, this, placeholders::error()));
                                                                   ^
In file included from /usr/include/boost/asio.hpp:82:0,
                 from BoostStomp.cpp:30:

---

**Comment by spatchola** [comment]
# the problem is solved :D i downloaded an old version of Boost v1.53 instead of v1.6

thank for your help :+1:
